const data = [
  {
    id: '1',
    job_role: 'Desenvolvedor',
    admission_date: '19/08/2018',
    birthdate: '12/04/1992',
    project: 'Project Backend Test',
    name: 'Juliano Reis',
    url: require('../../assets/img/naver.png'),
  },
  {
    id: '2',
    job_role: 'Desenvolvedor',
    admission_date: '19/08/2018',
    birthdate: '12/04/1992',
    project: 'Project Backend Test',
    name: 'Gabriel do Couto',
    url: require('../../assets/img/naver.png'),
  },
  {
    id: '3',
    job_role: 'Front-end Developer',
    admission_date: '19/08/2018',
    birthdate: '12/04/1992',
    project: 'Project Backend Test',
    name: 'Eduardo Bittencourt',
    url: require('../../assets/img/naver.png'),
  },
  {
    id: '4',
    job_role: 'Desenvolvedor',
    admission_date: '19/08/2018',
    birthdate: '12/04/1992',
    project: 'Project Backend Test',
    name: 'Gustavo Pinho',
    url: require('../../assets/img/naver.png'),
  },
  {
    id: '5',
    job_role: 'Front-end Developer',
    admission_date: '19/08/2018',
    birthdate: '12/04/1992',
    project: 'Project Backend Test',
    name: 'Christian Tavares',
    url: require('../../assets/img/naver.png'),
  },
  {
    id: '6',
    job_role: 'Designer',
    admission_date: '19/08/2018',
    birthdate: '12/04/1992',
    project: 'Project Backend Test',
    name: 'Christian Bittencourt',
    url: require('../../assets/img/naver.png'),
  },
  {
    id: '7',
    job_role: 'Desenvolvedor',
    admission_date: '19/08/2018',
    birthdate: '12/04/1992',
    project: 'Project Backend Test',
    name: 'Tavares Bittencourt',
    url: require('../../assets/img/naver.png'),
  },
  {
    id: '8',
    job_role: 'Front-end Developer',
    admission_date: '19/08/2018',
    birthdate: '12/04/1992',
    project: 'Project Backend Test',
    name: 'Gustavo Bittencourt',
    url: require('../../assets/img/naver.png'),
  },
  {
    id: 9,
    job_role: 'Back-end Developer',
    admission_date: '19/08/2018',
    birthdate: '12/04/1992',
    project: 'Project Backend Test',
    name: 'Christian Pinho',
    url: require('../../assets/img/naver.png'),
  },
];

export { data as default };
